---

name: Build Docker images for FIO Prometheus exporter

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '11 23 * * 0'

jobs:

  build_latest_image_from_main:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: master
          path: ./

      - name: Checkout Exporter Repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./exporter
          repository: mwennrich/fio_benchmark_exporter

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devopsansiblede/prometheus-fio-exporter:latest
          no-cache: true
          context: ./exporter/
          file: ./exporter/Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: "Import GPG key from secrets"
        uses: "crazy-max/ghaction-import-gpg@v5"
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          passphrase: "${{ secrets.GPG_PASS }}"
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: "./"

      - name: Last Build Date
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" ./README.md

      - name: "Commit last built information"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message:    "Last built information"
          commit_user_name:  "GitHub Actions"
          commit_user_email: "github.actions@macwinnie.me"
          repository:        "./"
